#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg PFSENSE_VERSION=2.6.0 -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"